spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# CONFIGURACION BASE DE DATOS POSTGRESQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/blueprintsdb}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURACION BASE DE DATOS JPA
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}


# CONFIGURACIONES DE POSTGRE
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
